language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t faraz891/docker-react -f Dockerfile .

script:
  - docker run -e CI=true faraz891/docker-react npm run test
