language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t faraz891/docker-react -f .

script:
  - docker run -e CI=true faraz891/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-175159307822"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY 

   
